### ISSUE TITLE
Allocate rooms & Allocate Teacher

### ISSUE THREAD

**Issue by Mon1elc** [anthonygoslar/lms-issues#12]
Part Time_A classes that are TRUE  not appearing in allocate teacher & allocate room views
Part Time_B  same as above
Morn_GE_IELTS not appearing apart from allocate student to class view.

**Comment by anthonygoslar** [comment]
Part Time_A & Part Time_A - these are not in the calendar. So the classes don't exist for the teacher & student to be allocated to them. I can assist you with this if you like?

Morn_GE_IELTS - This was a bug. 

Actions taken:
- Added manage_bl_occurrences as a post_save LectureChoice signal.

**Comment by Mon1elc** [comment]
Hi, happy New Year Anthony!!

Hope this year brings better circumstances for all…!

Re: below email, yes please I need this to show in calendar, I don’t know why they disappeared and I am able to allocate students to them , as per below:
[cid:image001.png@01D6E017.6BD1CEB0]

Thanks for helping.

**Comment by Mon1elc** [comment]
Please send me the times and days of the week on which these should happen.
I'll add them to the calendar for you.

Regards
Anthony Goslar
+27 82 928 0621
